### ISSUE TITLE
Execution aem-analyser of goal com.adobe.aem:aemanalyser-maven-plugin:1.0.2:project-analyse failed: Argument must not be null

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#72]
When the project to be analysed is not referencing a SDK API version the following error can be observed: 
```
[ERROR] Failed to execute goal com.adobe.aem:aemanalyser-maven-plugin:1.0.2:project-analyse (aem-analyser) on project accesscontroltool-package: Execution aem-analyser of goal com.adobe.aem:aemanalyser-maven-plugin:1.0.2:project-analyse failed: Argument must not be null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.adobe.aem:aemanalyser-maven-plugin:1.0.2:project-analyse (aem-analyser) on project accesscontroltool-package: Execution aem-analyser of goal com.adobe.aem:aemanalyser-maven-plugin:1.0.2:project-analyse failed: Argument must not be null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution aem-analyser of goal com.adobe.aem:aemanalyser-maven-plugin:1.0.2:project-analyse failed: Argument must not be null
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 10 common frames omitted
Caused by: java.lang.IllegalArgumentException: Argument must not be null
	at org.apache.sling.feature.ArtifactId.<init>(ArtifactId.java:72)
	at com.adobe.aem.analyser.mojos.VersionUtil.getSDKArtifactId(VersionUtil.java:169)
	at com.adobe.aem.analyser.mojos.AemAnalyseMojo.execute(AemAnalyseMojo.java:199)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 11 common frames omitted
```

This is due to the fact that `useVersion` in https://github.com/adobe/aemanalyser-maven-plugin/blob/1f0175400f3071838566c185aa43b2fcee16b433/aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/mojos/VersionUtil.java#L169 is null despite the fact that the plugin retrieved a correct last SDK version from Maven Central (https://github.com/adobe/aemanalyser-maven-plugin/blob/1f0175400f3071838566c185aa43b2fcee16b433/aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/mojos/VersionUtil.java#L156). The `useVersion` variable needs to be set to `foundVersion` in all circumstances, so this line https://github.com/adobe/aemanalyser-maven-plugin/blob/1f0175400f3071838566c185aa43b2fcee16b433/aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/mojos/VersionUtil.java#L167 must be moved out of the if block.

**Comment by cziegeler** [comment]
I've created a potential fix in PR #74
